### ISSUE TITLE
EDIFCellInst.setCellType needed?

### ISSUE THREAD

**Issue by jakobwenzel** [Xilinx/RapidWright#117]
Hi!

I am unsure about the use case of  `EDIFCellInst.setCellType` compared to `EDIFCellInst.updateCellType`. `setCellType` leaves the `EDIFPortInst`s pointing to the ports of the former cell, while `updateCellType` updates them.

Is it ever desirable to leave them pointing to the former cell?

This behavior was very confusing for me. It is very intuitive to call `setCellType` to change a CellType, so I used it in my code. When that produced invalid EDIF files, I modified `setCellType` to do more or less the same as `updateCellType`. When I later tidied up my code for submitting #116 I discovered the existence of `updateCellType`.

I would suggest having `setCellType` do the same as the current `updateCellType` (`updateCellType` would then either be deleted or just redirect to `setCellType` for backwards compatibility). If the old behaviour of `setCellType` is needed at all, it could be provided under a different name.

Kind Regards,
Jakob

**Comment by clavin-xlnx** [comment]
Hi Jakob,

I agree, these two method names are confusing and should be made more clear.  There are a number of places that `setCellType()` is called so I'll need to make sure they don't depend on the existing behavior before switching it over, but your request makes sense.  I'll provide an update after I can evaluate existing uses to see if there are any repercussions of the change.

Thanks!

Chris
