### ISSUE TITLE
Java 9+ Compliance: Dependency on JavaFX

### ISSUE THREAD

**Issue by jakobwenzel** [Xilinx/RapidWright#13]
Hi,

the class Job and its subclasses LocalJob and LSFJob use the class javafx.util.Pair.

To be compliant with Java Jigsaw, the project needs to declare a dependency on JavaFX. Because this is not done, the (gradle) build fails on Java 9+:

     .../com/xilinx/rapidwright/util/LocalJob.java:32: error: package javafx.util does not exist

Since only this one utility class is used, I would suggest to roll our own one instead of requiring another dependency.

Regards,
Jakob

**Comment by clavin-xlnx** [comment]
I agree and I am working on a replacement class to remove the JavaFX dependency.  I should have an update soon that should remove the reliance on JavaFX.
