### ISSUE TITLE
Add macro parameter mapping rules

### ISSUE THREAD

**Issue by gatecat** [Xilinx/RapidWright#162]
See SymbiFlow/fpga-interchange-schema#42 for more background

At the moment, the way that parameters are split up for primitives like distributed RAM and `LUT6_2` is not output into the resources. 

This will either need to be hardcoded into RapidWright, or included in the Vivado-derived database. I don't know how feasible the latter option would be.

**Comment by clavin-xlnx** [comment]
This appears to have been resolved per #213.

**Comment by gatecat** [comment]
Thanks, yes, this should be fine now!
