### ISSUE TITLE
Typo in EDIFCellInst documentation

### ISSUE THREAD

**Issue by snx90** [Xilinx/RapidWright#17]
Currently it reads:

> A cell instance in a logical (EDIF) netlist. Instantiates an EDIFCellInst. Created on: May 11, 2017

It should be:

> A cell instance in a logical (EDIF) netlist. Instantiates an EDIFCell. Created on: May 11, 2017

**Comment by clavin-xlnx** [comment]
Thank you, I have updated the Javadoc and source accordingly.
