### ISSUE TITLE
ArrayIndexOutOfBoundsException in tile.getBackwardsConnections

### ISSUE THREAD

**Issue by trharoldsen** [Xilinx/RapidWright#182]
I'm getting another ArrayIndexOutOfBoundsException with the getBackwardConnections in Spartan 7.  Using RapidWright version 2020.2.4.

```java
Device dev = Device.getDevice("xc7s25csga324-1");
Wire wire = dev.getWire("BRAM_INT_INTERFACE_L_X18Y45/INT_INTERFACE_LOGIC_OUTS_L0");
wire.getTile().getBackwardConnections(wire.getWireIndex());  // error happens here
```

**Comment by clavin-xlnx** [comment]
The [2020.2.5](https://github.com/Xilinx/RapidWright/releases/tag/v2020.2.5-beta) release should fix this issue.
