### ISSUE TITLE
EDIFNetlist.generateParentNetMap() StringIndexOutOfBoundsException when '/' used in cells/nets

### ISSUE THREAD

**Issue by DallonTG** [Xilinx/RapidWright#188]
On the latest version of RapidWright, I encounter this exception whenever EDIFNetlist.generateParentNetMap() is used on a flat design that has the hiearchy separator ('/') in cell and/or net names. Obviously it is non-ideal to have slashes in cell/net names. For my use-case, this occurs because Vivado infers a DSP in my design that I synthesize with "-flatten_hierarchy full" and uses a '/' in the inferred cell name and nets. I think this bug was introduced some time after the 2019.1.2 release.

```
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 19
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3720)
	at java.base/java.lang.String.substring(String.java:1909)
	at com.xilinx.rapidwright.edif.EDIFNetlist.getNetAliases(EDIFNetlist.java:994)
	at com.xilinx.rapidwright.edif.EDIFNetlist.generateParentNetMap(EDIFNetlist.java:1159)
	at com.xilinx.rapidwright.edif.EDIFNetlist.getParentNetMap(EDIFNetlist.java:1101)
```

Edit: I've realized this function is not in the RapidWright jars. The problem for me occurs in this code snippet of Netlist.getNetAliases():
```
while(checkInst == null && lastIndex > 0){
					// Check for cells with hierarchy separator in their name
					lastIndex = p.getHierarchicalInstName().lastIndexOf(EDIFTools.EDIF_HIER_SEP, lastIndex-1);
					instName = p.getHierarchicalInstName().substring(0, lastIndex);
					checkInst = getCellInstFromHierName(instName);
				}
```
Specifically, my DSP cell is called "test/counter_reg" (`p.getHierarchicalInstName()` here)  and the internal net the function is called for is"test/counter_reg/P[13]". `lastIndex` gets set to -1 inside this loop and so  the next line fails with the exception above. It seems another check for `lastIndex > 0` just needs to be added here.

**Comment by clavin-xlnx** [comment]
Thanks for pointing out this error.  Would you be able to share a design (any design) that exhibits this issue?

**Comment by DallonTG** [comment]
I thought I had isolated the issue to what I described, but I have unfortunately been able to replicate the issue. The problem may have been caused by me renaming some nets, etc. using TCL in Vivado prior to importing the design into RapidWright. I will reopen this issue if I encounter it again (and can provide an example).
