### ISSUE TITLE
Add missing cell pin default connections

### ISSUE THREAD

**Issue by clavin-xlnx** [Xilinx/RapidWright#199]
Track the issue SymbiFlow/fpga-interchange-tests#40.  The goal is to provide cell pin default connections for a new instance.

**Comment by mkurc-ant** [comment]
Is there a chance for having this information included in device resource in foreseeable future? I don't think that Vivado itself currently provides that information.

**Comment by clavin-xlnx** [comment]
@mkurc-ant  Please take a look at the latest commit (https://github.com/Xilinx/RapidWright/commit/c53114453da6327c9b708a8f4ccde081aa7105f4), I've attempted to populate the Interchange Device schema with cell pin static default values per @gatecat technique of extracting from Vivado.

**Comment by mkurc-ant** [comment]
@clavin-xlnx Thanks, I'll look into data produced with this change.

**Comment by clavin-xlnx** [comment]
Closing for now, please reopen if any issues are found with the data.
