### ISSUE TITLE
RapidWright Jupyter setup instructions should be copy and pastable

### ISSUE THREAD

**Issue by mithro** [Xilinx/RapidWright#21]
The instructions on the docs here -> http://www.rapidwright.io/docs/RapidWright_Jupyter_Setup.html use a lot of screenshots which make it impossibe to copy+paste the output into your notebook.

Could we get code section we can copy and paste.

**Comment by clavin-xlnx** [comment]
Certainly.  I will add them with my next update which should be quite soon.
