### ISSUE TITLE
Missing OBUFDS_DUAL_BUF definition in 7-series macro library

### ISSUE THREAD

**Issue by mkurc-ant** [Xilinx/RapidWright#212]
Device resources stored using the FPGA interchange format for any 7-series FPGA are missing definition of the `OBUFDS_DUAL_BUF` macro in the macro library. This prevents nextpnr from correctly expanding `OBUFDS`.

The macro is also not present in the `hdi_primitives.edf.test` file in RapidWright whereas its counterpart for `OBUFTDS` - `OBUFTDS_DUAL_BUF` is there.

https://github.com/YosysHQ/nextpnr/issues/773

**Comment by clavin-xlnx** [comment]
This was actually reported by @gatecat in #209 and can be worked around by using the patch mentioned there.  It will be fixed in the next release.

**Comment by mkurc-ant** [comment]
Alright, thanks. Looks like gatecat was faster than me with reporting this issue.
