### ISSUE TITLE
LUT route-thru equation gets altered if a net passes it twice (LUT5 and LUT6)

### ISSUE THREAD

**Issue by mkurc-ant** [Xilinx/RapidWright#226]
The issue surfaces for the `Murax` SoC design routed using `nextpnr-interchange` for which the routed physical netlist was converted by RapidWright to `dcp` and then read into Vivado. Possibly it shows up in other more complex designs too.

There are at least 3 nets there that are routed according to the following scheme: driver -> routing -> LUT6 -> routing -> LUT5 -> sink. Both LUT6 and LUT5 are route-thru and are at the same LUT BEL of a SLICE. The picture below shows an example of the situation for the ALUT BEL of a SLICE:

![image](https://user-images.githubusercontent.com/47315577/130790306-d40d0c82-5c32-4a4f-a9d1-eb0d5ba2a085.png)

![image](https://user-images.githubusercontent.com/47315577/130789589-b76dcccc-cb85-444d-8d4e-90400b9ccb4d.png)

As it is visible in the picture RapidWright / Vivado did not preserve the A4 to O6 and A5 to O5 connections thinking that if they belong to the same net then the LUT equation can be altered so that the net enters only via A5 and forks to O5 and O6 there. However, that would work only if both A4 and A5 pins were driven by the same driver but in this case they are not and altering the LUT equation breaks the route. Ultimately the design does not work in hardware correctly.

Apart from the net entering and exiting the SLICE twice being suboptimal, neither RapidWright nor Vivado should change the LUT equation. They should preserve what's present in a physical netlist.

**Comment by eddieh-xlnx** [comment]
Test for this scenario now in #262.
