### ISSUE TITLE
How to convert a Cell from one Unisim model to another?

### ISSUE THREAD

**Issue by mithro** [Xilinx/RapidWright#25]
I would like to convert a cell from an async flipflop (`Unisim.FDCE`)  to a sync flipflop (`Unisim.FDCE`).

I was thinking I could create a new cell, copy across all the properties + pin settings and then delete the old cell. However, cells don't seem to have a `listProperties` or similar function? (It has a `getProperty` and `addProperty` functions...)

I can imagine wanting to replace a `Unisim.AND` with `Unisim.LUT2` or `Unisim.LUT4` so it would be nice if there was a helper function for doing this.

**Comment by clavin-xlnx** [comment]
the `addProperty()` and `getProperty()` methods on `Cell` are convenience/helper methods that call down to their underlying `EDIFCellInst` equivalents (which are open source).   These convenience methods make code simpler.

I will add a few more helper methods to `Cell` to get properties and set properties but they are maps that use `EDIFName` and `EDIFPropertyValue` objects.

**Comment by eddieh-xlnx** [comment]
Closed due to inactivity.
