### ISSUE TITLE
EDIFPortInst linked to the wrong SitePinInst

### ISSUE THREAD

**Issue by GBrics** [Xilinx/RapidWright#293]
I'm using a DCP file generated with Vivado (implemented on xc7a100t).
I'm trying to get all the SitePinInst connected to the input of a given Cell (a CARRY4 in this example) by using the .getSitePinFromPortInst() function :

```
for( EDIFPortInst edifPort : myCarry4.getEDIFCellInst().getPortInsts()) { 
    if(edifPort.isInput()) {
        siteWires.clear();
        System.out.println("---------------");
        System.out.println(edifPort);
        System.out.println(myCarry4.getSitePinFromPortInst(edifPort, siteWires));
        System.out.println(siteWires);
        }
}
```

This piece of code returns :

```
---------------
o_s_reg[3]_i_1/DI[3]
IN SLICE_X4Y145.DX
[DCY0_OUT, DX]
---------------
o_s_reg[3]_i_1/DI[2]
IN SLICE_X4Y145.CX
[CCY0_OUT, CX]
---------------
o_s_reg[3]_i_1/DI[1]
IN SLICE_X4Y145.BX
[BCY0_OUT, BX]
---------------
o_s_reg[3]_i_1/DI[0]
IN SLICE_X4Y145.AX
[ACY0_OUT, AX]
        ...
```

The returned SitePinInst are wrong for the DI[3:0] ports (DX, CX, BC, AX instead of  D5, C1, B2, A2) as you can see on this screenshot on Vivado Device View : 

![carry4](https://user-images.githubusercontent.com/86125190/142019446-460c0b85-40ff-4118-a6cd-5bcdbdfaace2.JPG)

The first siteWire is correct (DCY0, CCY0, BCY0, ACY0) but the multiplexed wire is not correct (it should return the wire routed through the LUT/O5).

Am I doing it wrong? 

[top_adder_tester_routed.zip](https://github.com/Xilinx/RapidWright/files/7548063/top_adder_tester_routed.zip)

**Comment by clavin-xlnx** [comment]
Thank you for bringing this up, I was able to reproduce your results and it seems like `Cell.getSitePinFromPortInst()` is giving inconsistent results.  It appears that it is not taking into account the current routed state of the `SiteInst` and so it is only returning what would be the solution in the absence of a routed site.  We have some work to do make this API (and others) consistent and more predictable.

Here is how you can accomplish what you want with existing code:
```
        Design d = Design.readCheckpoint("top_adder_tester_routed.dcp");        
        Cell myCarry4 = d.getCell("adder_1_inst/o_s_reg[3]_i_1"); 
        for( EDIFPortInst edifPort : myCarry4.getEDIFCellInst().getPortInsts()) { 
            if(edifPort.isInput()) {
                System.out.println("---------------");
                System.out.println(edifPort);
                String siteWire = myCarry4.getSiteWireNameFromLogicalPin(edifPort.getName());
                Net net = myCarry4.getSiteInst().getNetFromSiteWire(siteWire);
                String sitePinName = DesignTools.getRoutedSitePin(myCarry4, net, edifPort.getName());
                SitePinInst sitePin = myCarry4.getSiteInst().getSitePinInst(sitePinName);
                System.out.println(sitePin);
            }
        }
```

I think the method `Cell.getSitePinFromPortInst()` was written with the assumption that the site was not routed, which, even when a cell is placed is generally not true.  This method should probably be augmented to examine site routing and use that as a hint and default to the other answer in the absence of no site routing.

**Comment by clavin-xlnx** [comment]
If you take a look at the source code of `DesignTools.getRoutedSitePin()` it calls a similar method that traces back to the site pin:

https://github.com/Xilinx/RapidWright/blob/005f1ce94742c36dc68e94123778b54a3af3f979/src/com/xilinx/rapidwright/design/DesignTools.java#L1474

Inside of a site, there are `BELPin` objects and Site Wire objects.  Site wires are represented in RapidWright simply as a named wires (`String` or `int` index inside the site).  Site wires connect `BELPin` objects electrically like a net.  To represent routing in the site, site wires are mapped to `Net` objects.  You can get the net of a site wire with the API `SiteInst.getNetFromSiteWire()` as used in the code above.  Navigating around `BELPin` and Site Wires can be achieved by using the APIs such as `BELPin.getSiteConns()` and `SiteInst.getSiteWirePins(String siteWireName)`.  

One other part of navigating site routing is `SitePIP` objects.  These are essentially programmable connections from an input `BELPin` to an output `BELPin` on a routing `BEL`.  The net using a `SitePIP` is not directly mapped to a net, but can be implicitly determined by the net mapping of the site wires immediately attached to activated `SitePIP`.  `SiteInst` objects store which `SitePIP` objects are turned on of off.  That can be accessed through `SiteInst.getUsedSitePIP()` where you pass in either a `BELPin` or the name of the `BEL`.  

Hope that helps.

**Comment by GBrics** [comment]
Indeed,  the source code of 'getRoutedSitePinFromPhysicalPin' provide a perfect example of what I was trying to do.
Thanks for the help !
