### ISSUE TITLE
ERROR: Don't know net of RAMB18_X0Y44/RDCLK

### ISSUE THREAD

**Issue by Db2515** [Xilinx/RapidWright#31]
I am trying to create a Module from a checkpoint file and metadata generated for an component that has been implemented out of context. However during I get the following Exception:
Exception in thread "main" java.lang.RuntimeException: ERROR: Don't know net of RAMB18_X0Y44/RDCLK
	at com.xilinx.rapidwright.design.MetadataParser.parse(MetadataParser.java:361)
	at com.xilinx.rapidwright.design.Module.<init>(Unknown Source)
	at DottyStitcher.loadModule(DottyStitcher.java:136)
	at DottyStitcher.main(DottyStitcher.java:157)

I am trying generate a design for the Basys 3 board (part namexc7a35tcpg236-1) and code for the component I am using can be found here: https://github.com/Db2515/FPGA_Rapid_Render/tree/VGA/components/VGA_output

And I have attached the checkpoint and metadata files 
[out.tar.gz](https://github.com/Xilinx/RapidWright/files/3195473/out.tar.gz)

Please let me know if you require anymore details

Cheers,

Daniel

**Comment by clavin-xlnx** [comment]
Hi Daniel,

The problem occurs in that some sites in our devices will support more than one type of functionality (primary type vs. alternate types).  Sometimes, pin names can differ for for an alternate type if it is used and a lookup was failing during the parsing of the metadata.  I committed a fix to support alternate site types and was able to resolve the error you reported (See [d59e181](https://github.com/Xilinx/RapidWright/commit/d59e181cf23ed6e67f964a6e0b3301fc90319943)).  

Thanks for reporting the issue.

Chris
