### ISSUE TITLE
Getting the "tied value" of a node

### ISSUE THREAD

**Issue by daveshah1** [Xilinx/RapidWright#32]
If you click on a VCC or GND node in Vivado, a "Tied value" item appears in the property pane thus:
![Screenshot from 2019-05-29 16-35-27](https://user-images.githubusercontent.com/5521177/58570422-e0e9c000-822f-11e9-8494-f60c299f001b.png)

Would it be possible to add a function in RapidWright to get this (if there isn't one already that I've missed?) For now it seems like looking for "VCC_WIRE" or "GND_WIRE" in the node name should work, but this doesn't feel like the cleanest solution.

**Comment by clavin-xlnx** [comment]
Yes, this is a good idea.  These attributes also show up using the `report_property [get_nodes <node>]` Tcl command with attributes `IS_GND` and `IS_VCC`.  I'm working on the 2019.1.0 RapidWright release now and I will update the device database files to include this information.

**Comment by daveshah1** [comment]
I see that `Node.isTiedToGnd()` and `Node.isTiedToVcc()` functions have been added in 2019.1 and are working for me. Thanks!
