### ISSUE TITLE
Net.connect() cannot connect to nets that originate in a different level of hierarchy

### ISSUE THREAD

**Issue by clavin-xlnx** [Xilinx/RapidWright#355]
See discussion in #351

**Comment by eddieh-xlnx** [comment]
@clavin-xlnx How should we move towards resolving this in light of https://github.com/Xilinx/RapidWright/pull/379?

**Comment by clavin-xlnx** [comment]
I think all the pieces are in place to make this work, just need to make the change and create appropriate tests.

**Comment by eddieh-xlnx** [comment]
@clavin-xlnx Since #379 is in, can we close this now?

**Comment by clavin-xlnx** [comment]
> @clavin-xlnx Since #379 is in, can we close this now?

I don't think this has been fixed yet.
