### ISSUE TITLE
getPhysicalPinMapping where the logical pin maps to more than one physical pin

### ISSUE THREAD

**Issue by daveshah1** [Xilinx/RapidWright#37]
When using a RAMB36E2, control inputs to the cell map to two physical bel pins (for the upper and lower halves) - see the below screenshot.
![Screenshot from 2019-06-19 17-01-22](https://user-images.githubusercontent.com/5521177/59781542-ec228f80-92b3-11e9-9262-eb8131e34d9d.png)

`Cell.getPhysicalPinMapping` only returns a single String, and therefore only returns one of the physical pins that the cell pin maps to. It is possible to work around this by iterating over `getPinMappingsP2L` and looking for all the physical pins with a given logical pin mapping, but it would be nice to have a function that returned all the physical pins a logical pin maps to.

**Comment by clavin-xlnx** [comment]
This is a special case situation and is less common.  I can add an API such as `List<String> Cell.getAllPhysicalPinMappings(String logicalPinName)` if that helps.

**Comment by daveshah1** [comment]
Yes, I would find that a useful addition.

**Comment by daveshah1** [comment]
Thanks, I can confirm `Cell.getAllPhysicalPinMappings(String logicalPinName)` in RapidWright 2019.1 is working for me.
