### ISSUE TITLE
DesignTools.routeIntraSiteNet() clobbers O6 instead of using O5

### ISSUE THREAD

**Issue by eddieh-xlnx** [Xilinx/RapidWright#392]
`DesignTools.routeIntraSiteNet` called to replace an existing C3 -> CFF.D connection via O5 that looks like this:

![image](https://user-images.githubusercontent.com/90657806/164058459-a3b4150b-ed38-424f-a748-33c0ebbfdb43.png)

but chooses to clobber the existing O6 connection:

![image](https://user-images.githubusercontent.com/90657806/164058851-ad8d39b8-31a0-4a87-9c77-9a42127f11ae.png)

**Comment by eddieh-xlnx** [comment]
@clavin-xlnx This was fixed by #394, right?

**Comment by clavin-xlnx** [comment]
Correct, closing.
