### ISSUE TITLE
EDIFPort.getBusName() now includes `[` suffix

### ISSUE THREAD

**Issue by eddieh-xlnx** [Xilinx/RapidWright#560]
e.g. it now returns `foo[`.

Appears to be a regression caused by #547.

**Comment by clavin-xlnx** [comment]
This is now by design for multi-bit ports.  I don't see a regression error, are we looking for an update to the Javadocs of the API?

**Comment by eddieh-xlnx** [comment]
Regression is that prior to #547 it did not return the `[` suffix, and it caused some code breakage.

**Comment by eddieh-xlnx** [comment]
Solution: accept that EDIFPort.getBusName() is a change from before, and document this change. Provide an alternate API which will not return `[`.

**Comment by eddieh-xlnx** [comment]
Fixed by #574.
