### ISSUE TITLE
[Site with dual output site pins (COUT, HQ2)] concurrent.ExecutionException at writeCheckpoint

### ISSUE THREAD

**Issue by nqdtan** [Xilinx/RapidWright#572]
I attach the zip file that contains the DCP for reproducing the issue here. Below is my RapidWright code

```java
public class TestCmp {
  public static void main(String[] args) {
    Design design = Design.readCheckpoint("test_cmp.dcp", "test_cmp.edf");
    design.writeCheckpoint("test_cmp_rw.dcp");
  }
}
```

I got the following error

> Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at com.xilinx.rapidwright.util.ParallelismTools.joinFirst(ParallelismTools.java:246)
	at b.b(Unknown Source)
	at b.a(Unknown Source)
	at com.xilinx.rapidwright.design.Design.writeCheckpoint(Unknown Source)
	at com.xilinx.rapidwright.examples.TestCmp.main(TestCmp.java:31)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.xilinx.rapidwright.util.ParallelismTools.joinFirst(ParallelismTools.java:244)
	... 4 more
...

When trying to isolate the problem, I suspect the error might have something to do with a net on which there are two output Site pins coming from the same SLICE. My workaround is replacing one of the PIPs connecting to these Site pins with a fresh one created by the `getPIP()` method from a Device object.

```java
public class TestCmp {                                                              
  public static void main(String[] args) {                                          
    Design design = Design.readCheckpoint("test_cmp.dcp", "test_cmp.edf");
    Device dev = design.getDevice();  

    PIP toRemovePIP = null;                                                         
    Net cmpNet = design.getNet("cmp");                                              
    for (PIP pip : cmpNet.getPIPs()) {                                              
      if (pip.toString().equals("CLE_E_CORE_X57Y168/CLE_E_CORE.CLE_SLICEM_TOP_1_COUT_PIN->>CLE_SLICEM_TOP_1_COUT")) {
        toRemovePIP = pip;                                                          
        break;                                                                      
      }                                                                             
    }                                                                               
    cmpNet.removePIP(toRemovePIP);                                                  
    cmpNet.addPIP(dev.getPIP(toRemovePIP.toString()));
    //System.out.println(toRemovePIP.deepHashCode() + " vs. " + dev.getPIP(toRemovePIP.toString()).deepHashCode());
    design.writeCheckpoint("test_cmp_rw.dcp");                   
  }                                                                              
} 
```

And `writeCheckpoint` runs OK. The issue of this workaround is that, when I load the generated DCP in Vivado, the net delay becomes approximated as shown in the following screenshot. This would impact the delay calculation in Vivado `report_timing`.

![Screenshot from 2022-11-02 17-45-26](https://user-images.githubusercontent.com/4418452/199628305-4c3a74b0-574f-409f-aea3-f05faf862f13.png)

I think the PIP in the original design has some special flag set on it, as its value returned by `deepHashCode()` is different from the PIP retrieved by name via the `Device` object. Maybe that's why it causes Vivado to approximate the delay, so this workaround is not ideal.

[test_cmp.zip](https://github.com/Xilinx/RapidWright/files/9925019/test_cmp.zip)

**Comment by clavin-xlnx** [comment]
This is fixed in the branch `2022.1.4`, which will be released soon.
