### ISSUE TITLE
RWRoute routes to additional, unnecessary pins

### ISSUE THREAD

**Issue by clavin-xlnx** [Xilinx/RapidWright#621]
To reproduce:
[example.zip](https://github.com/Xilinx/RapidWright/files/10935988/example.zip)
```
unzip example.zip
java com.xilinx.rapidwright.rwroute.RWRoute placed.dcp output_routed.dcp --nonTimingDriven
```
When reading the result back into Vivado, `report_route_status` returns:
```
report_route_status
Design Route Status
                                               :      # nets :
   ------------------------------------------- : ----------- :
   # of logical nets.......................... :        4738 :
       # of nets not needing routing.......... :        1044 :
           # of internally routed nets........ :         835 :
           # of nets with no loads............ :          50 :
           # of implicitly routed ports....... :         159 :
       # of routable nets..................... :        3694 :
           # of unrouted nets................. :         106 :
           # of fully routed nets............. :        1979 :
       # of nets with routing errors.......... :        1664 :
           # of nets with some unrouted pins.. :         823 :
           # of nets with resource conflicts.. :        1579 :
           # of nets with antennas/islands.... :        1156 :
   ------------------------------------------- : ----------- :
```
Looking at a specific net (`ipr[15]`) with a conflict, it would appear that the router routed to additional sinks unnecessarily for reasons unknown:
![image](https://user-images.githubusercontent.com/20803522/224156103-a9f8b5ad-aac9-49d0-af67-9d62b43913cc.png)
![image](https://user-images.githubusercontent.com/20803522/224156286-3da5f413-cd0f-43e8-814d-ff1f713c59cb.png)

**Comment by clavin-xlnx** [comment]
Sources for the placed design in Interchange format
[interchange_src.zip](https://github.com/Xilinx/RapidWright/files/10938587/interchange_src.zip)

**Comment by eddieh-xlnx** [comment]
Looks like the input DCP was corrupted (originally and incorrectly converted from the Interchange format, which [now](https://github.com/Xilinx/RapidWright/pull/627) detects this occurrence).
