### ISSUE TITLE
SLRCrosserGenerator not surpport U50- "xcu50-fsvh2104-2-e"

### ISSUE THREAD

**Issue by XDH-233** [Xilinx/RapidWright#628]
==============================================================================
==                           SLRCrosserGenerator                            ==
==============================================================================
Exception in thread "main" java.lang.RuntimeException: 

	ERROR: Couldn't identify  xcu50-fsvh2104-2-e in RapidWright part database. 
	at com.xilinx.rapidwright.device.PartNameTools.getPart(PartNameTools.java:112)
	at com.xilinx.rapidwright.examples.SLRCrosserGenerator.main(SLRCrosserGenerator.java:599)
	at R2Plus1D.PlaceDemo$.main(PlaceDemo.scala:6)
	at R2Plus1D.PlaceDemo.main(PlaceDemo.scala)

**Comment by clavin-xlnx** [comment]
Thank you for the issue.  I am not able to reproduce the issue you are seeing with the latest version of RapidWright.  Starting from a clean install:
```bash
git clone https://github.com/Xilinx/RapidWright.git
cd RapidWright
./gradlew compileJava
```
Then to run the SLRCrosserGenerator, I had to change some of the defaults to make it work for the xcu50:
```
java -cp bin:jars/* com.xilinx.rapidwright.examples.SLRCrosserGenerator -p xcu50-fsvh2104-2-e -b BUFGCE_X0Y0 -l LAGUNA_X0Y0
```
The output I got was:
```
==============================================================================
==                           SLRCrosserGenerator                            ==
==============================================================================
                    Init:     3.080s
          Create Netlist:     0.044s
     Place SLR Crossings:     0.090s
INFO: Building uncommon Wire->Node cache...
      This might take a few seconds for large devices on the first call.  
      It is generally triggered when getting the Node from an uncommon Wire object.  
      To avoid printing this message, set Device.QUIET_MESSAGE=true or set the ENVIRONMENT variable RW_QUIET_MESSAGE=1.
INFO: Finished building uncommon Wire->Node cache
      Custom Clock Route:    26.007s
           Route VCC/GND:     0.025s
     (Build XDEF Header):            (    0.010s)
            (Write EDIF):            (    0.113s)
(Write XDEF Cache (2/3)):            (    0.096s)
(Write XDEF Cache (1/3)):            (    0.098s)
(Write XDEF Cache (3/3)):            (    0.124s)
  (Write XDEF Placement):            (    0.195s)
    (Write XDEF Routing):            (    0.362s)
 (Write XDEF Finalizing):            (    0.006s)
            (Write XDEF):            (    0.396s)
       Write EDIF & XDEF:     0.407s
               Write XDC:     0.008s
------------------------------------------------------------------------------
         [No GC] *Total*:    29.662s
Wrote final DCP: slr_crosser.dcp

```

Perhaps your RapidWright installation/setup is not up to date?  Try [updating](https://github.com/Xilinx/RapidWright#how-to-update-rapidwright-to-the-latest-revision) or reinstalling afresh to see if the problem persists.
