### ISSUE TITLE
distinguishing const0 driven by LUT

### ISSUE THREAD

**Issue by jgoeders** [Xilinx/RapidWright#648]
I have a design (attached) with a CARRY4.  DI[3] and DI[2] are driven by const0, coming from a nearby TIEOFF.  

S[3] is driven by the output of a nearby LUT (shown below), where INIT = 0 (creating a constant 0).  Vivado doesn't seem to acknowledge that this LUT is used in the design, and the wire is marked as part of the GLOBAL_LOGIC0 net.  Can rapidwright distinguish this?  

When I try:
```python
print(cell.getEDIFCellInst().getPortInst("S[3]").getNet())
```
I just get:
```
<const0>
```
which suggests it also can't tell me that the signal is coming from this nearby LUT.  I just thought I would confirm.

![image](https://user-images.githubusercontent.com/1851142/230996909-520c5ffd-26a3-4066-9813-f42cc1853fab.png)
[design.zip](https://github.com/Xilinx/RapidWright/files/11193948/design.zip)

**Comment by clavin-xlnx** [comment]
Yes, it is possible to discover this scenario in RapidWright.  There is no actual cell placed on the D6LUT BEL, but you can discern that the LUT should be implicitly configured as a GND generator based on the site wire annotation being set to the GND net called `GLOBAL_LOGIC0`.  

I couldn't tell for sure from the picture above, but it seems like you are examining `SLICE_X2Y121` and the `CARRY4` cell is `count_i_reg[12]_i_6`.

To look deeper at this example, you'll want to examine it from the physical netlist side of things, here some Python code to illustrate:

```python
import rapidwright
from com.xilinx.rapidwright.design import Design
design = Design.readCheckpoint("design.dcp")
cell = design.getCell("count_i_reg[12]_i_6") # This is the physical cell corresponding to the CARRY4 
siteWireName = cell.getSiteWireNameFromLogicalPin("S[3]")
print(siteWireName)
print(cell.getSiteInst().getNetFromSiteWire(siteWireName))
```
Resulting output should be: 
```
D6LUT_O6
GLOBAL_LOGIC0
```
Here the site wire highlighted in Vivado:
![image](https://user-images.githubusercontent.com/20803522/231017943-28e03f94-b4b8-442d-a483-2e3df0ef4f06.png)

To answer your question, if you wanted to discover all the occurrences of these implicit GND LUTs, you could search through all the `SiteInst` objects of a design searching for site wires that are set to `GLOBAL_LOGIC0` and check if there is no cell at the corresponding BEL and that it is a LUT:

```python
# ...continuing from from the code above
from com.xilinx.rapidwright.device.BELPin import Direction
for i in design.getSiteInsts():
    for s in i.getSiteWiresFromNet(design.getGndNet()):
        output = i.getSite().getBELPins(s)[0];
        if output.getDir() == Direction.OUTPUT and output.getBEL().isLUT() and i.getCell(output.getBEL()) == None:
            print(i.getSiteName() + " " + s + " " + output.toString())
```  
outputs:
```
SLICE_X2Y121 D6LUT_O6 D6LUT.O6
```
Based on this, it would seem this only occurs once in the example design.  Give this a try to see if you have any other designs where you might be discovering these GND LUTs.

**Comment by jgoeders** [comment]
Thank you! Terrific response as always :) 

Sorry, I meant to mention the cell name was in fact `count_i_reg[12]_i_6`

**Comment by jgoeders** [comment]
This worked great.  Thanks.
