### ISSUE TITLE
RW reports CLK_INVERTED as 1'b1 when it is reported as 1'b0 in Vivado

### ISSUE THREAD

**Issue by reillymck** [Xilinx/RapidWright#748]
This error happens if just a couple designs out of the 35 designs that I am running. Basically, sometimes on a RAM32S primitive, rapidwright reports that the CLK_INVERTED property value is "1'b1", when in Vivado it is reported as "1'b0". The device viewer also shows the net being routed through the normal clk input on the slice.
Attached is python code/dcp to replicate and a screenshot of the vivado cell properties,
I am using Vivado 2023.1, but I do believe I ran into this error with checkpoints generated in Vivado 2022.2, I am just now getting around to submitting the issue.
[clk_inverted_py.txt](https://github.com/Xilinx/RapidWright/files/12015330/clk_inverted_py.txt)
![vivado_viewer](https://github.com/Xilinx/RapidWright/assets/50156344/e2527355-640f-485f-97a5-9c4f8c25bc66)
[design.zip](https://github.com/Xilinx/RapidWright/files/12015332/design.zip)
[design_edf.txt](https://github.com/Xilinx/RapidWright/files/12015333/design_edf.txt)

**Comment by clavin-xlnx** [comment]
It turns out that there are some older prims (`RAM32X1S_1` and `RAM16X1S_1`) that get retargeted to RAM32X1S that were polluting the property `IS_CLK_INVERTED`.  The original instance has this set to `1'b0` and was getting overwritten.  I will update the data file accordingly soon to resolve this.
