### ISSUE TITLE
Device data generate

### ISSUE THREAD

**Issue by the-centry** [Xilinx/RapidWright#849]
How to generate the device database rather than download the data?
Thanks!

**Comment by clavin-xlnx** [comment]
The RapidWright device database files are generated as part of an internal process.  It is currently not possible to do it externally.  Can you share what you would like to accomplish?  Perhaps we can help you in another way.

**Comment by the-centry** [comment]
> The RapidWright device database files are generated as part of an internal process. It is currently not possible to do it externally. Can you share what you would like to accomplish? Perhaps we can help you in another way.

Year, I want to know the device generate rule and change some data to create a device!

**Comment by clavin-xlnx** [comment]
> Year, I want to know the device generate rule and change some data to create a device!

Although the device model in RapidWright is part of the API library, another alternative would be to use the FPGA Interchange Format which is an open schema that enables an open source implementation of device models.  RapidWright fully supports the [FPGA Interchange Format](https://www.rapidwright.io/docs/FPGA_Interchange_Format.html) which has schemas to represent device models, and logical and physical netlists of partially or fully implemented designs.  In theory, you could export a device model from RapidWright in the FPGA Interchange Format device model and then modify it.

**Comment by the-centry** [comment]
> > Year, I want to know the device generate rule and change some data to create a device!
> 
> Although the device model in RapidWright is part of the API library, another alternative would be to use the FPGA Interchange Format which is an open schema that enables an open source implementation of device models. RapidWright fully supports the [FPGA Interchange Format](https://www.rapidwright.io/docs/FPGA_Interchange_Format.html) which has schemas to represent device models, and logical and physical netlists of partially or fully implemented designs. In theory, you could export a device model from RapidWright in the FPGA Interchange Format device model and then modify it.

A good idea! Thanks so much!
