### ISSUE TITLE
API to use vivado?

### ISSUE THREAD

**Issue by the-centry** [Xilinx/RapidWright#869]
Is there some api to use vivado in rapidwright? such as generate bit after dcp generated!
Thanks so much!

**Comment by clavin-xlnx** [comment]
Sure, checkout `VivadoTools`: https://www.rapidwright.io/javadoc/com/xilinx/rapidwright/util/VivadoTools.html, there is a `writeBitstream()` API in that class.

**Comment by the-centry** [comment]
> Sure, checkout `VivadoTools`: https://www.rapidwright.io/javadoc/com/xilinx/rapidwright/util/VivadoTools.html, there is a `writeBitstream()` API in that class.

Thanks so much! I think a api to set vivado path is necessary, the api provided depend on env path so much!
