### ISSUE TITLE
All zero values in frames of placed cells

### ISSUE THREAD

**Issue by dg-deus** [Xilinx/RapidWright#960]
For validating correctness of designs, I wanted to see if some valid data is configured in bitstream. However, all the data printed in python console is zero.

So, to test related bitstream APIs work fine, I placed and routed the following simple circuit, and generated corresponding dcp and bitstream files with Vivado 2017.2.

```
module top(
    input   wire    a, b,
    output  wire    y    
    );    
    assign  y = a ^ b;    
endmodule
```

Then, to print bitstream frames used cells in the routed design, I ran the following Python codes with rapidwright-2023.1.4-standalone-win64.jar.

```
RwDesign = Design.readCheckpoint("myCircuit.dcp")
RwBitstream = Bitstream.readBitstream("myCircuit.bit")
RwConfigArr = RwBitstream.getConfigArray()

for RwCell in RwDesign.getCells():
  try:
    RwBlock = RwConfigArr.getConfigBlock(RwCell.getTile())
    for RwFrame in RwBlock.getFrames():
      print(RwFrame.toString(True))
  except Exception as e:
    print(RwCell, e)
```

I still all-zero frame data.
Am I missing something here?

Thank you in advance.

**Comment by clavin-xlnx** [comment]
The issue is that `Bitstream.getConfigArray()` just gets the initial state of the configuration array (which is all zeros to start).  In order to populate it with the contents of the bitstream, `Bitstream.configureArray()` needs to be called.
