### ISSUE TITLE
Alveo U250 DSP48E2_{X28|X29} cell: <LOCKED>(BEL: (unplaced))

### ISSUE THREAD

**Issue by RipperJ** [Xilinx/RapidWright#986]
Hi. When using `DesignTools.calculateUtilization(...)` on a design implemented on Alveo U250, the two columns of DSPs on the right side (beside the Vitis default static region) are locked and hence triggers exceptions in `public static Map<UtilizationType, Integer> calculateUtilization(Collection<SiteInst> siteInsts)`, when `c.getBELName()` is found null.

**Comment by clavin-xlnx** [comment]
Thank you for reporting this issue, please give #988 a try, it should resolve the NPE.

**Comment by RipperJ** [comment]
Yes #988 resolves this issue. Thanks.
